export { LandingPage } from "./landing-page"
export { LoginPage } from "./login-page"
export { SignupPage } from "./signup-page"
export { ForgotPasswordPage } from "./forgot-password-page"
export { DashboardPage } from "./dashboard-page"
export { InstructorDashboardPage } from "./instructor-dashboard-page"
export { CourseCreatePage } from "./course-create-page"
